name: Build & Test

on:
  push:
  schedule:
      - cron: '0 0 * * 0'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Environment Variables
        id: env
        run: echo "branch=${GITHUB_HEAD_REF:="main"}" >> $GITHUB_OUTPUT

      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.env.outputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:coverage

      - name: Post Code Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
